import { useEffect, useState } from 'react';
import { addMedia, approveRelease, approveUser, createApp, getAdminApps, getAuditLogs, getClients, getPendingUsers, getReleases, getServerRuntimeSettings, publishRelease, rejectRelease, rollbackRelease, submitRelease, uploadMedia, uploadReleasePackage } from '../api/echoServerClient';
import type { CurrentUser } from '../types/auth';
import { userCan } from '../types/auth';
import type { EchoApp, AppRelease } from '../types/catalog';

export function AdminPortalPage(props: { user: CurrentUser }) {
  const [tab, setTab] = useState<'dashboard' | 'users' | 'apps' | 'releases' | 'clients' | 'logs' | 'server'>('dashboard');
  return (
    <section className="admin-page"><aside className="admin-tabs"><h1>Admin Portal</h1><button className={tab === 'dashboard' ? 'active' : ''} onClick={() => setTab('dashboard')}>Dashboard</button>{userCan(props.user, 'users.approve') && <button className={tab === 'users' ? 'active' : ''} onClick={() => setTab('users')}>Users</button>}{userCan(props.user, 'apps.create') && <button className={tab === 'apps' ? 'active' : ''} onClick={() => setTab('apps')}>Apps & Media</button>}{userCan(props.user, 'releases.create') && <button className={tab === 'releases' ? 'active' : ''} onClick={() => setTab('releases')}>Releases</button>}{userCan(props.user, 'logs.view') && <button className={tab === 'clients' ? 'active' : ''} onClick={() => setTab('clients')}>Clients</button>}{userCan(props.user, 'logs.view') && <button className={tab === 'logs' ? 'active' : ''} onClick={() => setTab('logs')}>Audit Logs</button>}{userCan(props.user, 'server.settings.edit') && <button className={tab === 'server' ? 'active' : ''} onClick={() => setTab('server')}>Server Settings</button>}</aside><div className="admin-content">{tab === 'dashboard' && <AdminDashboard />}{tab === 'users' && <UsersAdmin />}{tab === 'apps' && <AppsAdmin />}{tab === 'releases' && <ReleasesAdmin />}{tab === 'clients' && <ClientsAdmin />}{tab === 'logs' && <LogsAdmin />}{tab === 'server' && <ServerSettingsAdmin />}</div></section>
  );
}

function AdminDashboard() {
  return <div><h2>Dashboard</h2><div className="stats-grid"><div className="stat">Users<span>Approval gate enabled</span></div><div className="stat">Releases<span>Review before publish</span></div><div className="stat">Clients<span>Check-ins tracked</span></div><div className="stat">Server Health<span>Online</span></div></div></div>;
}

function UsersAdmin() {
  const [users, setUsers] = useState<any[]>([]); const [error, setError] = useState('');
  function load() { getPendingUsers().then(setUsers).catch((err) => setError(err instanceof Error ? err.message : 'Failed to load users.')); }
  useEffect(load, []);
  return <div><h2>Pending Users</h2>{error && <p className="error">{error}</p>}{users.map((user) => <div className="row" key={user.id}><span><strong>{user.username}</strong> {user.displayName}</span><button onClick={() => approveUser(user.id).then(load)}>Approve</button></div>)}{users.length === 0 && <p className="muted">No pending users.</p>}</div>;
}

function AppsAdmin() {
  const [apps, setApps] = useState<EchoApp[]>([]); const [appId, setAppId] = useState('echo-watchtower-sc'); const [name, setName] = useState('Echo Watchtower SC'); const [shortDescription, setShortDescription] = useState('Echo app utility.'); const [fullDescription, setFullDescription] = useState('Managed through Echo App Center.'); const [message, setMessage] = useState(''); const [mediaFile, setMediaFile] = useState<File | null>(null); const [mediaType, setMediaType] = useState('library_banner'); const [bannerUrl, setBannerUrl] = useState('');
  function load() { getAdminApps().then(setApps).catch(() => undefined); }
  useEffect(load, []);
  async function saveApp() { await createApp({ id: appId, name, shortDescription, fullDescription, developer: 'Echo Apps', category: 'Utility', tags: [], visibility: 'published' }); setMessage('App created.'); await load(); }
  async function saveUrl() { await addMedia(appId, { type: mediaType, url: bannerUrl, sortOrder: 0 }); setMessage('Media URL added.'); await load(); }
  async function saveFile() { if (!mediaFile) return; await uploadMedia(appId, { type: mediaType, sortOrder: 0, file: mediaFile }); setMessage('Media file uploaded.'); await load(); }
  return <div><h2>Apps & Media</h2><div className="panel"><label>App ID<input value={appId} onChange={(e) => setAppId(e.target.value)} /></label><label>Name<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Short Description<input value={shortDescription} onChange={(e) => setShortDescription(e.target.value)} /></label><label>Full Description<textarea value={fullDescription} onChange={(e) => setFullDescription(e.target.value)} /></label><button onClick={saveApp}>Create App</button></div><div className="panel"><h3>Media</h3><label>Media Type<select value={mediaType} onChange={(e) => setMediaType(e.target.value)}><option value="icon">Icon</option><option value="library_banner">Library Banner</option><option value="store_banner">Store Banner</option><option value="screenshot">Screenshot</option></select></label><label>Upload File<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setMediaFile(e.target.files?.[0] ?? null)} /></label><button onClick={saveFile}>Upload Media File</button><label>Or Media URL<input value={bannerUrl} onChange={(e) => setBannerUrl(e.target.value)} /></label><button onClick={saveUrl}>Add Media URL</button></div>{message && <p className="success">{message}</p>}<div className="panel"><h3>Current Apps</h3>{apps.map((app) => <div key={app.id} className="row"><strong>{app.name}</strong><span>{app.visibility}</span><span>{app.media.length} media</span></div>)}</div></div>;
}

function ReleasesAdmin() {
  const [apps, setApps] = useState<EchoApp[]>([]); const [releases, setReleases] = useState<AppRelease[]>([]); const [appId, setAppId] = useState(''); const [version, setVersion] = useState('1.0.0'); const [platform, setPlatform] = useState('windows-x64'); const [entrypoint, setEntrypoint] = useState('echo-app.json'); const [channel, setChannel] = useState('stable'); const [file, setFile] = useState<File | null>(null); const [changelog, setChangelog] = useState('Initial release'); const [message, setMessage] = useState('');
  async function load() { const [a, r] = await Promise.all([getAdminApps(), getReleases()]); setApps(a); setReleases(r); if (!appId && a[0]) setAppId(a[0].id); }
  useEffect(() => { load().catch((err) => setMessage(err instanceof Error ? err.message : 'Failed to load releases.')); }, []);
  async function upload() { if (!file) { setMessage('Select a package file first.'); return; } await uploadReleasePackage(appId, { file, version, platform, channel, entrypoint, installType: 'portable', changelog }); setMessage('Release package uploaded as draft.'); await load(); }
  async function transition(id: string, action: 'submit' | 'approve' | 'publish' | 'reject' | 'rollback') { if (action === 'submit') await submitRelease(id); if (action === 'approve') await approveRelease(id); if (action === 'publish') await publishRelease(id); if (action === 'reject') await rejectRelease(id, 'Rejected from admin portal.'); if (action === 'rollback') await rollbackRelease(id); await load(); }
  return <div><h2>Releases</h2><div className="panel"><label>App<select value={appId} onChange={(e) => setAppId(e.target.value)}>{apps.map((app) => <option key={app.id} value={app.id}>{app.name}</option>)}</select></label><div className="details-grid"><label>Version<input value={version} onChange={(e) => setVersion(e.target.value)} /></label><label>Platform<select value={platform} onChange={(e) => setPlatform(e.target.value)}><option>windows-x64</option><option>linux-x64</option></select></label><label>Channel<select value={channel} onChange={(e) => setChannel(e.target.value)}><option>stable</option><option>beta</option><option>dev</option></select></label><label>Entrypoint<input value={entrypoint} onChange={(e) => setEntrypoint(e.target.value)} /></label></div><label>Package Zip<input type="file" accept=".zip" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><label>Changelog<textarea value={changelog} onChange={(e) => setChangelog(e.target.value)} /></label><button onClick={upload}>Upload Release Package</button></div>{message && <p className="muted">{message}</p>}<div className="panel"><h3>Release Queue</h3>{releases.map((release) => <div key={release.id} className="release-row"><div><strong>{release.appId}</strong> v{release.version}<small>{release.platform} • {release.channel} • {release.status}</small></div><div className="action-row"><button onClick={() => transition(release.id, 'submit')}>Submit</button><button onClick={() => transition(release.id, 'approve')}>Approve</button><button onClick={() => transition(release.id, 'publish')}>Publish</button><button onClick={() => transition(release.id, 'reject')}>Reject</button><button onClick={() => transition(release.id, 'rollback')}>Rollback</button></div></div>)}</div></div>;
}

function ClientsAdmin() { const [data, setData] = useState<{ clients: any[]; installReports: any[] }>({ clients: [], installReports: [] }); useEffect(() => { getClients().then(setData).catch(() => undefined); }, []); return <div><h2>Client Computers</h2><div className="panel">{data.clients.map((client) => <div key={client.id} className="row"><strong>{client.name}</strong><span>{client.platform}</span><span>{client.lastCheckInAt}</span><span>{client.installedApps?.length ?? 0} apps</span></div>)}{data.clients.length === 0 && <p className="muted">No client check-ins yet.</p>}</div><h3>Install Reports</h3><div className="panel">{data.installReports.map((report) => <div key={report.id} className="row"><strong>{report.appId}</strong><span>{report.action}</span><span>{report.status}</span><span>{report.message}</span></div>)}</div></div>; }
function LogsAdmin() { const [logs, setLogs] = useState<any[]>([]); useEffect(() => { getAuditLogs().then(setLogs).catch(() => undefined); }, []); return <div><h2>Audit Logs</h2><div className="panel">{logs.map((log) => <div key={log.id} className="row"><strong>{log.action}</strong><span>{log.targetType}</span><span>{log.createdAt}</span></div>)}</div></div>; }
function ServerSettingsAdmin() { const [settings, setSettings] = useState<any>(null); const [error, setError] = useState(''); useEffect(() => { getServerRuntimeSettings().then(setSettings).catch((err) => setError(err instanceof Error ? err.message : 'Failed to load server settings.')); }, []); return <div><h2>Server Settings</h2>{error && <p className="error">{error}</p>}{settings && <div className="panel"><p className="muted">Server host and port are controlled by `.env` and require a server restart.</p><div className="details-grid"><div><small>Host bind</small><strong>{settings.host}</strong></div><div><small>Port</small><strong>{settings.port}</strong></div><div><small>Public base URL</small><strong>{settings.publicBaseUrl}</strong></div><div><small>Data folder</small><strong>{settings.dataDir}</strong></div></div><pre>{`ECHO_SERVER_HOST=${settings.host}\nECHO_SERVER_PORT=${settings.port}\nECHO_PUBLIC_BASE_URL=${settings.publicBaseUrl}`}</pre></div>}</div>; }
